name: Build

on:
  push:
    tags: [ "[0-9]+.*" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Add Vcpkg
      run: vcpkg integrate install

    - name: Build
      run: msbuild -p:Configuration=Release
    
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        name: ${{ github.ref_name }}
        body: \#\#\# v${{ github.ref_name }} update.
        draft: false
        prerelease: false
        files: |
          Out/Hid.dll